apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: redis
  labels:
    run: redis
spec:
  containers:
  - image: redis123
    name: redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
