apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: frontendui
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-deployment-container
          image: nitinmanojkumar/tomcat-movie-front-end-image:latest
