apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: frontend-podcreated
      image: nitinmanojkumar/tomcat-movie-front-end-image:latest