apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset-pod
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      type: front-end
  template:
    metadata:
      name: frontendui
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: frontend-replicasetcreated
          image: nitinmanojkumar/tomcat-movie-front-end-image:latest
