apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-pod
  labels:
    name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      name: frontendui
      labels:
        name: myapp
    spec:
      containers:
        - name: frontend-deploymentcreated
          image: nitinmanojkumar/tomcat-movie-front-end-image:latest
