apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 8090
      port: 8090
      nodePort: 30008
  selector:
    app: myapp
  # type: NodePort  #NodePort/CusterIP/LoadBalancer
  # ports:
  #   - targetPort: 80
  #     #port num of the pod(optional if not provided takes port's port)
  #     port: 80
  #     #port num of the k8 service(mandatory to provide)
  #     nodePort: 30008
  #     #port num of the node valid range 30k-32k(optional takes any from the valid range if not provided)
