apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicaset-deployment
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 6
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: myapp-prod-reaplicaset-thru-deployment
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-replicasetdemo
          image: nginx
